name: Test Python

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and report coverage
        run: pytest --cov

      # - name: Run doctests
      #   run: python tests/docs/run_doc_examples.py

